import sys
import yaml
from PySide6.QtWidgets import (QApplication, QMainWindow, QSplitter, QTreeWidget, 
                             QTreeWidgetItem, QWidget, QVBoxLayout, QFormLayout, 
                                                          QLabel, QSpinBox, QCheckBox, QScrollArea, QGroupBox)
                                                          from PySide6.QtCore import Qt

                                                          class VisionSystemUI(QMainWindow):
                                                              def __init__(self, config_path):
                                                                      super().__init__()
                                                                              self.setWindowTitle("비전 시스템 통합 설정")
                                                                                      self.resize(800, 600)
                                                                                              
                                                                                                      # 1. 데이터 로드 (실제로는 로그인한 사용자의 level을 가져와야 함)
                                                                                                              with open(config_path, 'r', encoding='utf-8') as f:
                                                                                                                          self.config = yaml.safe_load(f)
                                                                                                                                  
                                                                                                                                          self.current_user_level = 3  # 예시: 관리자로 로그인했다고 가정
                                                                                                                                                  
                                                                                                                                                          # 2. UI 레이아웃 설정
                                                                                                                                                                  self.central_widget = QWidget()
                                                                                                                                                                          self.setCentralWidget(self.central_widget)
                                                                                                                                                                                  self.main_layout = QVBoxLayout(self.central_widget)
                                                                                                                                                                                          
                                                                                                                                                                                                  # 좌우 분할 (좌: 트리 메뉴, 우: 상세 설정창)
                                                                                                                                                                                                          self.splitter = QSplitter(Qt.Horizontal)
                                                                                                                                                                                                                  
                                                                                                                                                                                                                          # 트리 메뉴 생성
                                                                                                                                                                                                                                  self.tree = QTreeWidget()
                                                                                                                                                                                                                                          self.tree.setHeaderLabel("시스템 구조")
                                                                                                                                                                                                                                                  self.tree.itemClicked.connect(self.on_tree_clicked)
                                                                                                                                                                                                                                                          self.splitter.addWidget(self.tree)
                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                          # 우측 상세 설정창 (스크롤 가능 영역)
                                                                                                                                                                                                                                                                                  self.scroll = QScrollArea()
                                                                                                                                                                                                                                                                                          self.scroll.setWidgetResizable(True)
                                                                                                                                                                                                                                                                                                  self.detail_container = QWidget()
                                                                                                                                                                                                                                                                                                          self.detail_layout = QVBoxLayout(self.detail_container)
                                                                                                                                                                                                                                                                                                                  self.scroll.setWidget(self.detail_container)
                                                                                                                                                                                                                                                                                                                          self.splitter.addWidget(self.scroll)
                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                          self.main_layout.addWidget(self.splitter)
                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                          # 3. 트리 메뉴 동적 생성
                                                                                                                                                                                                                                                                                                                                                                  self.init_tree()

                                                                                                                                                                                                                                                                                                                                                                      def init_tree(self):
                                                                                                                                                                                                                                                                                                                                                                              """YAML 데이터를 기반으로 권한에 맞는 트리 구성"""
                                                                                                                                                                                                                                                                                                                                                                                      for module in self.config.get('modules', []):
                                                                                                                                                                                                                                                                                                                                                                                                  # 모듈 권한 체크
                                                                                                                                                                                                                                                                                                                                                                                                              if self.current_user_level < module.get('auth_level', 0):
                                                                                                                                                                                                                                                                                                                                                                                                                              continue
                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                          module_item = QTreeWidgetItem(self.tree, [module['label']])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  for unit in module.get('units', []):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  # 유닛 권한 체크
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if self.current_user_level < unit.get('auth_level', 0):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      continue
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      unit_item = QTreeWidgetItem(module_item, [unit['label']])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      unit_item.setData(0, Qt.UserRole, unit) # 실제 데이터 바인딩

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          def on_tree_clicked(self, item, column):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  """트리 항목 클릭 시 우측에 파라미터 위젯 생성"""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          unit_data = item.data(0, Qt.UserRole)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if not unit_data: return
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  # 기존 위젯 제거
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          for i in reversed(range(self.detail_layout.count())): 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      self.detail_layout.itemAt(i).widget().setParent(None)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          # 새로운 파라미터 그룹 생성
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  group_box = QGroupBox(f"{unit_data['label']} 설정")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          form_layout = QFormLayout()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          for p in unit_data.get('params', []):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      # 개별 파라미터 권한 및 위젯 생성
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  label = QLabel(p['label'])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              label.setToolTip(p.get('help', ""))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if p['type'] == 'int':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      widget = QSpinBox()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      widget.setRange(p.get('min', 0), p.get('max', 100))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      widget.setValue(p['value'])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              # 권한이 낮으면 읽기 전용 처리
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if self.current_user_level < p.get('auth_level', 0):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          widget.setEnabled(False)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  form_layout.addRow(label, widget)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      group_box.setLayout(form_layout)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              self.detail_layout.addWidget(group_box)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      self.detail_layout.addStretch() # 아래쪽 공백 채우기

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          app = QApplication(sys.argv)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              window = VisionSystemUI('system_config.yaml')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  window.show()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      sys.exit(app.exec())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      